compatibility with jekyll-assets
juusaw/amp-jekyll pull request #15
Opened 2016-11-22 23:24 UTC by publicarray

Changes the image file path. This allows source images to live in _assets and enable compatibility with https://github.com/jekyll/jekyll-assets

before: `~/myblog/assets/img/image.png`

after: `~/myblog/_site/assets/img/image.png`

2016-11-26 09:20 UTC, juusaw requested changes

2016-11-26 09:20 UTC, juusaw commented on amp_filter.rb
> +            src = File.join(Dir.pwd + '_site', image['src'])
Should the `_site` part in the path also be a separate parameter to `File.join`? In my local environment `pwd` didn't add the slash to the end and the path got malformed.

I would change `File.join(Dir.pwd + '_site', image['src'])` to `File.join(Dir.pwd, '_site', image['src'])`.

2016-11-26 23:33 UTC, publicarray commented on amp_filter.rb
> +            src = File.join(Dir.pwd + '_site', image['src'])
Good catch. Should I rebase the pull request, so that it fits into one commit?

2016-11-27 14:10 UTC, juusaw approved these changes

2016-11-27 14:12 UTC, merged